
CREATE STAGE LAW_S3_STAGE
URL = 's3://law-enf-data/dev/files/'
CREDENTIALS = (AWS_KEY_ID = 'AKIAZIBNJRHPXS7FKGSO' AWS_SECRET_KEY = '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');


CREATE STAGE LAW_S3_ARC
URL = 's3://law-enf-data/dev/archive/'
CREDENTIALS = (AWS_KEY_ID = 'AKIAZIBNJRHPXS7FKGSO' AWS_SECRET_KEY = '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');
